/**
 * Completion catalogue: common LaTeX commands and environments with Monaco
 * snippet bodies (`${1:placeholder}` tab stops) and the package they need.
 */

export interface CommandSpec {
  /** Name without backslash. */
  name: string;
  /** Snippet inserted after the backslash. */
  snippet: string;
  doc: string;
  pkg?: string;
  math?: boolean;
}

export interface EnvironmentSpec {
  name: string;
  /** Body snippet (inside \begin{name}…\end{name}); may include arguments right after \begin{name}. */
  args?: string;
  body?: string;
  doc: string;
  pkg?: string;
}

type Row = [name: string, snippet: string, doc: string, pkg?: string];

const TEXT: Row[] = [
  ['section', 'section{${1:Title}}', 'Numbered section'],
  ['section*', 'section*{${1:Title}}', 'Unnumbered section'],
  ['subsection', 'subsection{${1:Title}}', 'Numbered subsection'],
  ['subsubsection', 'subsubsection{${1:Title}}', 'Numbered sub-subsection'],
  ['chapter', 'chapter{${1:Title}}', 'Chapter (report/book)'],
  ['part', 'part{${1:Title}}', 'Part'],
  ['paragraph', 'paragraph{${1:Title}}', 'Run-in paragraph heading'],
  ['title', 'title{${1:Title}}', 'Document title'],
  ['author', 'author{${1:Name}}', 'Document author(s)'],
  ['date', 'date{${1:\\today}}', 'Document date'],
  ['maketitle', 'maketitle', 'Typeset the title block'],
  ['tableofcontents', 'tableofcontents', 'Table of contents'],
  ['listoffigures', 'listoffigures', 'List of figures'],
  ['listoftables', 'listoftables', 'List of tables'],
  ['appendix', 'appendix', 'Start the appendices'],
  ['textbf', 'textbf{${1:${TM_SELECTED_TEXT:text}}}', 'Bold text'],
  ['textit', 'textit{${1:${TM_SELECTED_TEXT:text}}}', 'Italic text'],
  ['emph', 'emph{${1:${TM_SELECTED_TEXT:text}}}', 'Emphasis'],
  ['underline', 'underline{${1:${TM_SELECTED_TEXT:text}}}', 'Underline'],
  ['texttt', 'texttt{${1:${TM_SELECTED_TEXT:text}}}', 'Monospace text'],
  ['textsc', 'textsc{${1:text}}', 'Small caps'],
  ['textsf', 'textsf{${1:text}}', 'Sans-serif text'],
  ['textrm', 'textrm{${1:text}}', 'Roman text'],
  ['textcolor', 'textcolor{${1:blue}}{${2:${TM_SELECTED_TEXT:text}}}', 'Coloured text', 'xcolor'],
  ['colorbox', 'colorbox{${1:yellow}}{${2:text}}', 'Text on a coloured background', 'xcolor'],
  ['footnote', 'footnote{${1:text}}', 'Footnote'],
  ['marginpar', 'marginpar{${1:note}}', 'Margin note'],
  ['href', 'href{${1:https://}}{${2:link text}}', 'Hyperlink', 'hyperref'],
  ['url', 'url{${1:https://}}', 'URL', 'hyperref'],
  ['label', 'label{${1:key}}', 'Label for cross-references'],
  ['ref', 'ref{${1:key}}', 'Reference a label'],
  ['eqref', 'eqref{${1:eq:key}}', 'Reference an equation (with parentheses)', 'amsmath'],
  ['pageref', 'pageref{${1:key}}', 'Page of a label'],
  ['autoref', 'autoref{${1:key}}', 'Reference with automatic name', 'hyperref'],
  ['cref', 'cref{${1:key}}', 'Clever reference', 'cleveref'],
  ['Cref', 'Cref{${1:key}}', 'Clever reference (capitalised)', 'cleveref'],
  ['cite', 'cite{${1:key}}', 'Citation'],
  ['citep', 'citep{${1:key}}', 'Parenthetical citation', 'natbib'],
  ['citet', 'citet{${1:key}}', 'Textual citation', 'natbib'],
  ['parencite', 'parencite{${1:key}}', 'Parenthetical citation (biblatex)', 'biblatex'],
  ['textcite', 'textcite{${1:key}}', 'Textual citation (biblatex)', 'biblatex'],
  ['nocite', 'nocite{${1:*}}', 'Include uncited references'],
  ['bibliography', 'bibliography{${1:references}}', 'BibTeX database(s)'],
  ['bibliographystyle', 'bibliographystyle{${1|plain,unsrt,alpha,abbrv,ieeetr,plainnat,unsrtnat,abbrvnat|}}', 'Bibliography style'],
  ['addbibresource', 'addbibresource{${1:references.bib}}', 'biblatex database', 'biblatex'],
  ['printbibliography', 'printbibliography', 'Print the biblatex bibliography', 'biblatex'],
  ['includegraphics', 'includegraphics[width=${1:0.8}\\linewidth]{${2:file}}', 'Insert an image', 'graphicx'],
  ['caption', 'caption{${1:Caption}}', 'Figure/table caption'],
  ['centering', 'centering', 'Centre the current environment'],
  ['input', 'input{${1:file}}', 'Insert another .tex file'],
  ['include', 'include{${1:file}}', 'Include a chapter file (new page)'],
  ['usepackage', 'usepackage{${1:package}}', 'Load a package'],
  ['documentclass', 'documentclass{${1|article,report,book,beamer,letter,memoir,scrartcl|}}', 'Document class'],
  ['newcommand', 'newcommand{\\\\${1:name}}[${2:0}]{${3:definition}}', 'Define a new command'],
  ['renewcommand', 'renewcommand{\\\\${1:name}}{${2:definition}}', 'Redefine a command'],
  ['newenvironment', 'newenvironment{${1:name}}{${2:begin}}{${3:end}}', 'Define an environment'],
  ['item', 'item ', 'List item'],
  ['newpage', 'newpage', 'Start a new page'],
  ['clearpage', 'clearpage', 'New page, flushing floats'],
  ['pagebreak', 'pagebreak', 'Page break'],
  ['linebreak', 'linebreak', 'Line break'],
  ['noindent', 'noindent', 'No paragraph indent'],
  ['vspace', 'vspace{${1:1em}}', 'Vertical space'],
  ['hspace', 'hspace{${1:1em}}', 'Horizontal space'],
  ['vfill', 'vfill', 'Fill vertical space'],
  ['hfill', 'hfill', 'Fill horizontal space'],
  ['smallskip', 'smallskip', 'Small vertical skip'],
  ['medskip', 'medskip', 'Medium vertical skip'],
  ['bigskip', 'bigskip', 'Big vertical skip'],
  ['today', 'today', "Today's date"],
  ['LaTeX', 'LaTeX{}', 'The LaTeX logo'],
  ['TeX', 'TeX{}', 'The TeX logo'],
  ['ldots', 'ldots', 'Ellipsis …'],
  ['textbackslash', 'textbackslash{}', 'Literal backslash'],
  ['pagestyle', 'pagestyle{${1|plain,empty,headings,fancy|}}', 'Page style'],
  ['thispagestyle', 'thispagestyle{${1|plain,empty|}}', 'Page style for this page'],
  ['setlength', 'setlength{\\\\${1:parindent}}{${2:0pt}}', 'Set a length'],
  ['hline', 'hline', 'Horizontal rule in a table'],
  ['toprule', 'toprule', 'Top rule (booktabs)', 'booktabs'],
  ['midrule', 'midrule', 'Middle rule (booktabs)', 'booktabs'],
  ['bottomrule', 'bottomrule', 'Bottom rule (booktabs)', 'booktabs'],
  ['cmidrule', 'cmidrule(lr){${1:1-2}}', 'Partial rule (booktabs)', 'booktabs'],
  ['multicolumn', 'multicolumn{${1:2}}{${2:c}}{${3:text}}', 'Span columns'],
  ['multirow', 'multirow{${1:2}}{*}{${2:text}}', 'Span rows', 'multirow'],
  ['lipsum', 'lipsum[${1:1-2}]', 'Dummy text', 'lipsum'],
  ['geometry', 'geometry{margin=${1:2.5cm}}', 'Page margins', 'geometry'],
  ['hypersetup', 'hypersetup{colorlinks=true, linkcolor=${1:blue}}', 'Configure hyperref', 'hyperref'],
  ['definecolor', 'definecolor{${1:name}}{HTML}{${2:3B5BDB}}', 'Define a colour', 'xcolor'],
  ['fancyhead', 'fancyhead[${1|L,C,R|}]{${2:text}}', 'Header (fancyhdr)', 'fancyhdr'],
  ['fancyfoot', 'fancyfoot[${1|L,C,R|}]{${2:text}}', 'Footer (fancyhdr)', 'fancyhdr'],
  ['titleformat', 'titleformat{\\\\${1:section}}{${2:\\\\Large\\\\bfseries}}{\\\\the${1}}{1em}{}', 'Heading format (titlesec)', 'titlesec'],
  ['setlist', 'setlist[${1:itemize}]{${2:leftmargin=*}}', 'Configure lists (enumitem)', 'enumitem'],
  ['onehalfspacing', 'onehalfspacing', '1.5 line spacing', 'setspace'],
  ['doublespacing', 'doublespacing', 'Double spacing', 'setspace'],
  ['todo', 'todo{${1:note}}', 'To-do note', 'todonotes'],
  ['SI', 'SI{${1:3.0}}{${2:\\\\metre\\\\per\\\\second}}', 'Number with unit', 'siunitx'],
  ['qty', 'qty{${1:3.0}}{${2:m}}', 'Quantity with unit', 'siunitx'],
  ['num', 'num{${1:12345}}', 'Formatted number', 'siunitx'],
  ['makeatletter', 'makeatletter', 'Allow @ in command names'],
  ['makeatother', 'makeatother', 'End of @-commands'],
];

const MATH: Row[] = [
  ['frac', 'frac{${1:a}}{${2:b}}', 'Fraction'],
  ['dfrac', 'dfrac{${1:a}}{${2:b}}', 'Display-style fraction', 'amsmath'],
  ['sqrt', 'sqrt{${1:x}}', 'Square root'],
  ['sum', 'sum_{${1:i=1}}^{${2:n}}', 'Summation'],
  ['prod', 'prod_{${1:i=1}}^{${2:n}}', 'Product'],
  ['int', 'int_{${1:a}}^{${2:b}}', 'Integral'],
  ['iint', 'iint', 'Double integral', 'amsmath'],
  ['oint', 'oint', 'Contour integral'],
  ['lim', 'lim_{${1:x \\\\to \\\\infty}}', 'Limit'],
  ['infty', 'infty', '∞'],
  ['partial', 'partial', '∂'],
  ['nabla', 'nabla', '∇'],
  ['cdot', 'cdot', '⋅'],
  ['times', 'times', '×'],
  ['leq', 'leq', '≤'],
  ['geq', 'geq', '≥'],
  ['neq', 'neq', '≠'],
  ['approx', 'approx', '≈'],
  ['equiv', 'equiv', '≡'],
  ['in', 'in', '∈'],
  ['subseteq', 'subseteq', '⊆'],
  ['forall', 'forall', '∀'],
  ['exists', 'exists', '∃'],
  ['rightarrow', 'rightarrow', '→'],
  ['Rightarrow', 'Rightarrow', '⇒'],
  ['leftrightarrow', 'leftrightarrow', '↔'],
  ['mapsto', 'mapsto', '↦'],
  ['mathbb', 'mathbb{${1:R}}', 'Blackboard bold (ℝ, ℕ, …)', 'amssymb'],
  ['mathcal', 'mathcal{${1:L}}', 'Calligraphic letter'],
  ['mathbf', 'mathbf{${1:x}}', 'Bold math'],
  ['mathrm', 'mathrm{${1:d}}', 'Upright math'],
  ['text', 'text{${1:text}}', 'Text inside math', 'amsmath'],
  ['operatorname', 'operatorname{${1:name}}', 'Operator name', 'amsmath'],
  ['left', 'left${1:(} ${2} \\\\right${3:)}', 'Auto-sized delimiters'],
  ['hat', 'hat{${1:x}}', 'Hat accent'],
  ['bar', 'bar{${1:x}}', 'Bar accent'],
  ['vec', 'vec{${1:v}}', 'Vector arrow'],
  ['dot', 'dot{${1:x}}', 'Dot accent (time derivative)'],
  ['overline', 'overline{${1:x}}', 'Overline'],
  ['binom', 'binom{${1:n}}{${2:k}}', 'Binomial coefficient', 'amsmath'],
  ['boldsymbol', 'boldsymbol{${1:\\\\alpha}}', 'Bold symbol', 'amsmath'],
  ['quad', 'quad', 'Quad space'],
  ['qquad', 'qquad', 'Double quad space'],
];

const GREEK = 'alpha beta gamma delta epsilon varepsilon zeta eta theta vartheta iota kappa lambda mu nu xi pi varpi rho varrho sigma varsigma tau upsilon phi varphi chi psi omega Gamma Delta Theta Lambda Xi Pi Sigma Upsilon Phi Psi Omega'.split(' ');

export const COMMANDS: CommandSpec[] = [
  ...TEXT.map(([name, snippet, doc, pkg]) => ({ name, snippet, doc, pkg })),
  ...MATH.map(([name, snippet, doc, pkg]) => ({ name, snippet, doc, pkg, math: true })),
  ...GREEK.map((g) => ({ name: g, snippet: g, doc: `Greek letter ${g}`, math: true })),
];

export const ENVIRONMENTS: EnvironmentSpec[] = [
  { name: 'itemize', body: '\\item ${1}', doc: 'Bulleted list' },
  { name: 'enumerate', body: '\\item ${1}', doc: 'Numbered list' },
  { name: 'description', body: '\\item[${1:Term}] ${2:Description}', doc: 'Description list' },
  { name: 'figure', args: '[${1:htbp}]', body: '\\centering\n\\includegraphics[width=0.8\\linewidth]{${2:file}}\n\\caption{${3:Caption}}\n\\label{fig:${4:label}}', doc: 'Floating figure', pkg: 'graphicx' },
  { name: 'table', args: '[${1:htbp}]', body: '\\centering\n\\caption{${2:Caption}}\n\\label{tab:${3:label}}\n\\begin{tabular}{${4:lcr}}\n\t${5}\n\\end{tabular}', doc: 'Floating table' },
  { name: 'tabular', args: '{${1:lcr}}', body: '${2}', doc: 'Table grid' },
  { name: 'center', body: '${1}', doc: 'Centred block' },
  { name: 'flushleft', body: '${1}', doc: 'Left-aligned block' },
  { name: 'flushright', body: '${1}', doc: 'Right-aligned block' },
  { name: 'quote', body: '${1}', doc: 'Short quotation' },
  { name: 'quotation', body: '${1}', doc: 'Long quotation' },
  { name: 'abstract', body: '${1}', doc: 'Abstract' },
  { name: 'verbatim', body: '${1}', doc: 'Verbatim text' },
  { name: 'minipage', args: '{${1:0.45}\\linewidth}', body: '${2}', doc: 'Mini page' },
  { name: 'equation', body: '${1}\n\\label{eq:${2:label}}', doc: 'Numbered equation' },
  { name: 'equation*', body: '${1}', doc: 'Unnumbered equation', pkg: 'amsmath' },
  { name: 'align', body: '${1:a} &= ${2:b} \\\\\\\\\n${3:c} &= ${4:d}', doc: 'Aligned equations', pkg: 'amsmath' },
  { name: 'align*', body: '${1:a} &= ${2:b}', doc: 'Aligned equations (unnumbered)', pkg: 'amsmath' },
  { name: 'gather', body: '${1}', doc: 'Gathered equations', pkg: 'amsmath' },
  { name: 'cases', body: '${1:x} & \\text{if } ${2:x > 0} \\\\\\\\\n${3:0} & \\text{otherwise}', doc: 'Piecewise definition', pkg: 'amsmath' },
  { name: 'pmatrix', body: '${1:a} & ${2:b} \\\\\\\\ ${3:c} & ${4:d}', doc: 'Matrix with parentheses', pkg: 'amsmath' },
  { name: 'bmatrix', body: '${1:a} & ${2:b} \\\\\\\\ ${3:c} & ${4:d}', doc: 'Matrix with brackets', pkg: 'amsmath' },
  { name: 'proof', body: '${1}', doc: 'Proof', pkg: 'amsthm' },
  { name: 'theorem', body: '${1}', doc: 'Theorem (define with \\newtheorem)' },
  { name: 'lstlisting', args: '[language=${1:Python}]', body: '${2}', doc: 'Code listing', pkg: 'listings' },
  { name: 'tikzpicture', body: '\\draw (0,0) -- (${1:1},${2:1});', doc: 'TikZ drawing', pkg: 'tikz' },
  { name: 'axis', args: '[${1}]', body: '\\addplot {${2:x^2}};', doc: 'PGFPlots axis', pkg: 'pgfplots' },
  { name: 'multicols', args: '{${1:2}}', body: '${2}', doc: 'Multiple columns', pkg: 'multicol' },
  { name: 'subfigure', args: '{${1:0.45}\\linewidth}', body: '\\centering\n\\includegraphics[width=\\linewidth]{${2:file}}\n\\caption{${3}}', doc: 'Sub-figure', pkg: 'subcaption' },
  { name: 'frame', args: '{${1:Title}}', body: '${2}', doc: 'Beamer slide' },
  { name: 'block', args: '{${1:Title}}', body: '${2}', doc: 'Beamer block' },
  { name: 'columns', body: '\\column{0.5\\textwidth}\n${1}\n\\column{0.5\\textwidth}\n${2}', doc: 'Beamer columns' },
  { name: 'algorithm', args: '[${1:htbp}]', body: '\\caption{${2:Algorithm}}\n\\begin{algorithmic}[1]\n\t\\State ${3}\n\\end{algorithmic}', doc: 'Algorithm float', pkg: 'algorithm' },
  { name: 'tcolorbox', args: '[title=${1:Title}]', body: '${2}', doc: 'Coloured box', pkg: 'tcolorbox' },
  { name: 'document', body: '${1}', doc: 'Document body' },
];
